package main

import (
	"flag"
	"fmt"
	"os"
	"strings"
)

func rawLines() []string {
	suites := []string{"DeploymentGate", "RetryPolicy", "InventoryClient", "SentinelScan"}
	lines := []string{"CI bootstrap: loading runner configuration"}
	for _, suite := range suites {
		lines = append(lines, fmt.Sprintf("suite %s: discovered 30 tests", suite))
		for index := 1; index <= 30; index++ {
			lines = append(lines, fmt.Sprintf("PASS %s :: case-%02d (%d ms)", suite, index, 10+(index%7)))
		}
	}
	return append(lines,
		"WARN transient connection retry 1/3",
		"WARN transient connection retry 2/3",
		"FAIL InventoryClient :: rejects-expired-token",
		"AssertionError: expected status 403, received 200",
		"  at inventory/client_test.go:84",
		"Summary: 120 passed, 1 failed, 121 total",
	)
}

func compactLines() []string {
	return []string{
		"[SIMULATED COMPACT OUTPUT — not generated by RTK]",
		"FAILED: 1/121 tests",
		"InventoryClient :: rejects-expired-token",
		"AssertionError: expected status 403, received 200",
		"at inventory/client_test.go:84",
		"120 passed; 1 failed",
	}
}

func byteCount(lines []string) int { return len(strings.Join(lines, "\n")) + 1 }
func printLines(lines []string)     { fmt.Println(strings.Join(lines, "\n")) }

func main() {
	mode := flag.String("mode", "compare", "raw, compact, or compare")
	flag.Parse()
	raw, compact := rawLines(), compactLines()
	switch *mode {
	case "raw":
		printLines(raw)
	case "compact":
		printLines(compact)
	case "compare":
		fmt.Println("variant,lines,bytes,approx_tokens_bytes_div_4")
		fmt.Printf("raw,%d,%d,%d\n", len(raw), byteCount(raw), (byteCount(raw)+3)/4)
		fmt.Printf("compact,%d,%d,%d\n\n", len(compact), byteCount(compact), (byteCount(compact)+3)/4)
		printLines(compact)
	default:
		fmt.Fprintln(os.Stderr, "usage: noisy-ci --mode <raw|compact|compare>")
		os.Exit(2)
	}
	os.Exit(1)
}
