#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

namespace {

std::vector<std::string> raw_lines() {
    const std::vector<std::string> suites{
        "DeploymentGate", "RetryPolicy", "InventoryClient", "SentinelScan"};
    std::vector<std::string> lines{"CI bootstrap: loading runner configuration"};
    for (const auto& suite : suites) {
        lines.push_back("suite " + suite + ": discovered 30 tests");
        for (int index = 1; index <= 30; ++index) {
            std::ostringstream line;
            line << "PASS " << suite << " :: case-" << std::setw(2) << std::setfill('0')
                 << index << " (" << 10 + (index % 7) << " ms)";
            lines.push_back(line.str());
        }
    }
    lines.push_back("WARN transient connection retry 1/3");
    lines.push_back("WARN transient connection retry 2/3");
    lines.push_back("FAIL InventoryClient :: rejects-expired-token");
    lines.push_back("AssertionError: expected status 403, received 200");
    lines.push_back("  at tests/inventory_client_test.cpp:84");
    lines.push_back("Summary: 120 passed, 1 failed, 121 total");
    return lines;
}

std::vector<std::string> compact_lines() {
    return {
        "[SIMULATED COMPACT OUTPUT -- not generated by RTK]",
        "FAILED: 1/121 tests",
        "InventoryClient :: rejects-expired-token",
        "AssertionError: expected status 403, received 200",
        "at tests/inventory_client_test.cpp:84",
        "120 passed; 1 failed",
    };
}

std::size_t bytes(const std::vector<std::string>& lines) {
    std::size_t result = 0;
    for (const auto& line : lines) result += line.size() + 1;
    return result;
}

void print(const std::vector<std::string>& lines) {
    for (const auto& line : lines) std::cout << line << '\n';
}

}  // namespace

int main(int argc, char** argv) {
    std::string mode = "compare";
    if (argc == 3 && std::string(argv[1]) == "--mode") mode = argv[2];
    const auto raw = raw_lines();
    const auto compact = compact_lines();

    if (mode == "raw") print(raw);
    else if (mode == "compact") print(compact);
    else if (mode == "compare") {
        std::cout << "variant,lines,bytes,approx_tokens_bytes_div_4\n";
        std::cout << "raw," << raw.size() << ',' << bytes(raw) << ',' << (bytes(raw) + 3) / 4 << '\n';
        std::cout << "compact," << compact.size() << ',' << bytes(compact) << ',' << (bytes(compact) + 3) / 4 << "\n\n";
        print(compact);
    } else {
        std::cerr << "usage: noisy_ci --mode <raw|compact|compare>\n";
        return 2;
    }
    return 1;
}
